### PR TITLE
Update wine to 9.0 stable

### PR DESCRIPTION
**Pull request by Gcenx**
A minimal build that was built & linked against `libfreetype.6.dylib` that’s included.

### CODE REVIEW

**Comment by nrlquaker** [comment]
@Gcenx thank you so much.
@belthesar can you please merge and create new build?

**Comment by nrlquaker** [comment]
@belthesar please check the GitHub Action `check_sha512` for some reason it fails.

**Comment by belthesar** [comment]
Mikrotik's CDN has been changed to prevent directly linking to the download package.  Looking to see if there's a Mikrotik published hash we can use, otherwise, we may have to check in a hash with the update as the validation source.

**Comment by nrlquaker** [comment]
@belthesar I think the `check_sha512` should only run in `winbox.exe` is changed.
Can you please merge and create new build?

**Pull request merged**
