### PR TITLE
bump to wine-8.0

### PR DESCRIPTION
**Pull request by Gcenx**
Quickly thrown together, didn't bump the app version etc

### CODE REVIEW

**Comment by Gcenx** [comment]
Marking as draft so affected users can test to see if this helps or not else there’s at least one patch I’m aware of that might help.

once I’ve build/published wine-8.4 packages I’ll rebuild this to be more minimal.

**Comment by nrlquaker** [comment]
@Gcenx thanks for a quick response. Btw the release is larger by 26mb vs the 7.0 one.
I've created a [pre-release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.37.1) for affected users to test.
At the moment I don't have access to MikroTik router.

**Comment by Gcenx** [comment]
> @Gcenx thanks for a quick response. Btw the release is larger by 26mb vs the 7.0 one.
> I've created a [pre-release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.37.1) for affected users to test.
> At the moment I don't have access to MikroTik router.

It’s not too surprising this package is simply my Winehq wine-8.0 build with i386 stripped

Upstream wine-7.0 onward had started to import a number of libraries directly into wine, it ahoy or be possible to disable as many of these as possible and shrink the dylibs down again for a final reversion of this actually resolved the issues.

**Comment by nrlquaker** [comment]
@Gcenx pre-release was made from your PR.

**Comment by nrlquaker** [comment]
@Gcenx can you please build `wine 8.0.1 stable`?

**Comment by nrlquaker** [comment]
@Gcenx I've created release with wine 8.1 devel from your repo.
Seems like everything is fine. Can you please build a min version?

**Pull request closed without merging**
