### PR TITLE
Update winbox to 3.40

### PR DESCRIPTION
**Pull request by juanpedrojose**
Update Winbox x64 executable to 3.40

### CODE REVIEW

**Comment by nrlquaker** [comment]
@belthesar please check if hash of `winbox64.exe` is the same as if downloaded from the offsite.

**Comment by belthesar** [comment]
I'll look at this later today

**Comment by belthesar** [comment]
From the PR:

```
┌─[ winbox-mac/Winbox-mac.app/Contents/Resources ] on  pr/juanpedrojose/131
└─▪ sha512sum winbox64.exe
430cbeac13e5c424bbe21581a36b6b060baaa00d674566b3850bc79a5fa7976ff57383754e2977edd5bec9e06b2dd19c89b1c8613049e530c1032eed7e9e1b3c  winbox64.exe

┌─[ winbox-mac/Winbox-mac.app/Contents/Resources ] on  pr/juanpedrojose/131
└─▪ ls -la winbox64.exe
-rw-r--r--  1 belthesar  staff  2292568 Oct 18 10:47 winbox64.exe
```

From Mikrotik:
```
┌─[ ~/Downloads ]
└─▪ sha512sum winbox64.exe
84d577f1abea69df8dd6ddb5636e2129def89f75ee7160286cd8f385a28b25388a00349850033351b1d78916344c7ff15baf2da60c9c362999cfe4cd9c161b0e  winbox64.exe

┌─[ ~/Downloads ]
└─▪ ls -la winbox64.exe
-rw-r--r--@ 1 belthesar  staff  2290008 Oct 18 10:58 winbox64.exe
```

This file does not have the same hash, nor does it have the same size. VirusTotal does not flag the file, but this PR can't be accepted unless the hash matches.

**Comment by ZPrimed** [comment]
Nice catch @belthesar , I hope this was an honest mistake and not a "supply-chain attack" attempt 😨

**Comment by juanpedrojose** [comment]
I cannot validate the statement above:
```winbox-mac/Winbox-mac.app/Contents/Resources on  feature/3.40
➜ curl -s https://download.mikrotik.com/winbox/3.40/winbox64.exe | shasum -a 512
430cbeac13e5c424bbe21581a36b6b060baaa00d674566b3850bc79a5fa7976ff57383754e2977edd5bec9e06b2dd19c89b1c8613049e530c1032eed7e9e1b3c  -

winbox-mac/Winbox-mac.app/Contents/Resources on  feature/3.40
➜ shasum -a 512 winbox64.exe
430cbeac13e5c424bbe21581a36b6b060baaa00d674566b3850bc79a5fa7976ff57383754e2977edd5bec9e06b2dd19c89b1c8613049e530c1032eed7e9e1b3c  winbox64.exe

winbox-mac/Winbox-mac.app/Contents/Resources on  feature/3.40
➜ ls -l winbox64.exe
-rw-r--r--  1 alex  staff  2292568 Oct 10 15:31 winbox64.exe

winbox-mac/Winbox-mac.app/Contents/Resources on  feature/3.40
➜ curl -o ./winbox64_mikrotik.exe https://download.mikrotik.com/winbox/3.40/winbox64.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2238k  100 2238k    0     0  2235k      0  0:00:01  0:00:01 --:--:-- 2250k

winbox-mac/Winbox-mac.app/Contents/Resources on  feature/3.40 [?]
➜ shasum -a 512 winbox64_mikrotik.exe
430cbeac13e5c424bbe21581a36b6b060baaa00d674566b3850bc79a5fa7976ff57383754e2977edd5bec9e06b2dd19c89b1c8613049e530c1032eed7e9e1b3c  winbox64_mikrotik.exe

**Comment by m1ron0xFF** [comment]
```
curl -s https://download.mikrotik.com/winbox/3.40/winbox64.exe | shasum -a 512
430cbeac13e5c424bbe21581a36b6b060baaa00d674566b3850bc79a5fa7976ff57383754e2977edd5bec9e06b2dd19c89b1c8613049e530c1032eed7e9e1b3c  -
```

**Comment by nrlquaker** [comment]
@belthesar please double check. Seems like hashes are the same.

**Comment by belthesar** [comment]
I will have a look in the next few days. I'm currently on vacation,
returning Friday. 

On November 5, 2023, GitHub ***@***.***> wrote:
> @belthesar <https://github.com/belthesar> please double check. Seems
> like hashes are the same.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/nrlquaker/winbox-mac/pull/131#issuecomment-
1793737474>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AANPALSNB6MMN45FXRBNJNDYC6HZVAVCNFSM6AAAAAA6AMGJSOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJTG4ZTONBXGQ>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by nrlquaker** [comment]
@juanpedrojose thanks!

**Pull request merged**
