### PR TITLE
add support for non-english user

### PR DESCRIPTION
**Pull request by samlm0**
Change LC_CTYPE to "LANG" which in environment variables

### CODE REVIEW

**Comment by samlm0** [comment]
compare

**Comment by nrlquaker** [comment]
@samlm0 
Does it fix the issue on the second launch?
Seems like `LC_CTYPE` is still `en_US.UTF-8` on non first launch.

**Comment by samlm0** [comment]
> @samlm0 Does it fix the issue on the second launch? Seems like `LC_CTYPE` is still `en_US.UTF-8` on non first launch.

Let me fix that

**Comment by samlm0** [comment]
nvm, just found out $LANG in macOS app mode is not exists, re-set the LC_CTYPE via applescript

**Comment by nrlquaker** [comment]
I've tested it. After launch app is immediately closes and in some time winbox launches.
From the user point of view it looks like crash. And winbox is launched with icon from exe, not from app.

**Comment by samlm0** [comment]
> I've tested it. After launch app is immediately closes and in some time winbox launches. From the user point of view it looks like crash. And winbox is launched with icon from exe, not from app.

I found another way to start winbox with icon, and with correct LANG

**Comment by samlm0** [comment]
found a bugs. 
1. launch winbox
2. login
3. resize window
4. the window can not resize correctly

temp solution
1. launch winbox
2. login
3. click [new winbox] on the left sidebar
4. try resize on the new winbox window
5. all winbox windows can resize correctly

**Comment by samlm0** [comment]
found a solusion, start winbox absolute path. need verify

only test on my local machine

**Comment by nrlquaker** [comment]
Can someone interested in non-english support test this please?

**Comment by nrlquaker** [comment]
ping @cmmchina @coolchenK @bazzelio @SirPrikol @Error996 @wmbin

**Comment by nrlquaker** [comment]
@samlm0 sorry for a long response. Does this PR fix the resize issue #109 ?

**Comment by wmbin** [comment]
@nrlquaker   It can be used normally,but opening windows is slow
Sorry, my english isn't good

**Comment by samlm0** [comment]
@nrlquaker i try to upgrade the wine to 8.0

it seem run soomthly, and add a font smoothing fix on is

**Comment by nrlquaker** [comment]
@samlm0 can you rebase please? WIne is already 8.1.

**Comment by belthesar** [comment]
Yeah, I was just thinking that we should close this as stale. Should the PR author be interested in cleaning things up and resubmitting, the PR can be reopened.

**Pull request closed without merging**
